### ISSUE TITLE
monitor doesnt start

### ISSUE THREAD

**Issue by L4gash** [e1abrador/sub.Monitor#4]
Hi ,

Well after the custom the config.ini and upload the domains to db the monitor didnt start when i set the parameters, only show the banner :(

Any suggestions?

**Comment by e1abrador** [comment]
Hello!

Could you tell me the command you are using? In any case, I highly recommend you to read the README.md file, following those instructions you shouldn't have any issues.

Provide me with how you use the script, and I'll try to help you make it work.

**Comment by L4gash** [comment]
Sure, i read the README.md and follow step by step this jaja.

First i  set my .txt with the domains after this i upload with the command --add domain --file .txt.
Then i verified if this domaind are upload correctly with the command --list and yea they are uploaded correctly

And well at the end i run the monitor.py -d domain.com -h 1 .... and nothing happens 

The config.ini its configured to with the bins and api files.
![submonitor](https://github.com/e1abrador/sub.Monitor/assets/61742681/1dacadce-ad2d-4047-9398-488e0f1d6322)

Thanks a lot!

**Comment by e1abrador** [comment]
Ok, I see the problem, didn't notice that. Will fix it in the next version. I also tried on my VPS and there's the same problem.
Please, until this is fixed use the -df flag and add your domain to that .txt file. In that way will work. Don't close the ISSUE, leave it open until I fix this.

Command: ``python3 monitor.py -df your-root-domains.txt -h 1``

Thanks for alerting me about the problem ; ) will try to solve it ASAP.

**Comment by L4gash** [comment]
Thanks a lot bro you are the best now its working with the  -df command i will upload an evidence 
![image](https://github.com/e1abrador/sub.Monitor/assets/61742681/f2367c93-c2b0-4147-83c8-66ee5e4fbf17)

Regards!

**Comment by e1abrador** [comment]
Awesome, working as expected now!
As said, expect a solution for that in the next few days. 
Have a nice day!

**Comment by e1abrador** [comment]
Issue solved. Now replaced ``-d`` with ``-D`` and ``-h`` with ``-H``. Read the updated README to fully understand the workflow (is pretty much the same with little flags changed).

Have a nice day!
