### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)

### ISSUE THREAD

**Issue by halencarjunior** [e1abrador/sub.Monitor#5]
The requirements.txt could be changed to remove the line that contains the sqlite3 package from pip since it is part of standard lib on python3

Reference:
https://stackoverflow.com/questions/69591461/no-matching-distribution-found-for-sqlite3

**Comment by e1abrador** [comment]
Hello!

Thanks for opening the issue. I did remove the sqlite3 install from requirements.txt.

If you have any other issue regarding this project (or any other) feel free to open it again, and I'll be happy to check it. I'm closing the issue as it's now resolved.

Thanks again and have a nice day!
